### ISSUE TITLE
生成的pdf没有目录是正常的吗？

### ISSUE THREAD

**Issue by LuyaoMa-zju** [Jy-stdio/2021-ICM-D-Outstanding#1]
作者您好，我用vscode的latex workshop对PAPER.tex进行编译后生成的pdf没有目录（目录页只有Contents这个单词，没有任何目录内容），请问这种现象是正常的吗T_T

**Comment by liujiyaoFDU** [comment]
不太正常，你可以去这里试试下载我们这篇论文所使用的原版模板：
[https://github.com/xjtu-blacksmith/easymcm](https://github.com/xjtu-blacksmith/easymcm)
